Add support for Python 3.3
* Fix imports for Python 3
* Make test for string type compatible with Python 3
* Fix report_level settings for docutils. Details:
    The report_level option should be an integer according to
    http://docutils.sourceforge.net/docs/user/config.html#report-level
    With Python 3, because it's no longer allowed to compare strings and
    integers, passing a string causes this error:
        [..]/docutils/utils/__init__.py", line 188, in system_message
            if self.stream and (level >= self.report_level
        TypeError: unorderable types: int() >= str()
    The --quiet option corresponds to a report_level of 5, as we can see by
    reading the code in docutils/frontend.py
* Rename deprecated assertEquals into assertEqual
* Suppress py3 warnings about unclosed files
* Python 3 was printing a bunch of warnings such as:
    src/landslide/generator.py:234: ResourceWarning: unclosed file
    <_io.BufferedWriter name='presentation.html'>
* Update setup.py to mention Python 3.3 support
* Fix embedded image with Python 3: base64 encoded image data was
  wrapped with b'' in the data URL.
* Add travis config file
* Testing against multiple Python versions using tox